import { NextRequest, NextResponse } from 'next/server';
import { getAdminDb } from '@/lib/firebase-admin';
import { verifyAuth, authErrorResponse } from '@/lib/verify-auth';
import { createGitHubRepository } from '@/lib/github-integration';
import { ensureUserDocument } from '@/lib/ensure-user-doc';
import { buildEnvExampleFromKitsAndExistingKeys, buildKitFiles, type IntegrationKitId } from '@/lib/integration-kits';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

type UploadedImage = { id: string; name: string; dataUrl: string };

function splitGeneratedSiteFiles(html: string): { indexHtml: string; cssText: string; jsText: string } {
  let indexHtml = html;
  let cssText = '';
  let jsText = '';

  const cssTaggedMatch = html.match(/<style[^>]*id=["']app-styles["'][^>]*>([\s\S]*?)<\/style>/i);
  if (cssTaggedMatch) {
    cssText = cssTaggedMatch[1].trim();
    indexHtml = indexHtml.replace(cssTaggedMatch[0], '<link rel="stylesheet" href="assets/css/main.css" />');
  }

  const jsTaggedMatch = html.match(/<script[^>]*id=["']app-script["'][^>]*>([\s\S]*?)<\/script>/i);
  if (jsTaggedMatch) {
    jsText = jsTaggedMatch[1].trim();
    indexHtml = indexHtml.replace(jsTaggedMatch[0], '<script src="assets/js/main.js"></script>');
  }

  return { indexHtml, cssText, jsText };
}

function buildFileMap(params: {
  siteCode: string;
  siteRenderMode: 'frame-scroll' | 'video-hero';
  webpFrames?: string[];
  videoBase64?: string | null;
  uploadedImages?: UploadedImage[];
  enabledKits?: IntegrationKitId[];
  envKeys?: string[];
}): { [path: string]: string } {
  const { indexHtml, cssText, jsText } = splitGeneratedSiteFiles(params.siteCode);
  const files: Record<string, string> = {};

  files['README.md'] =
    `# Draftly 3D Website Export\n\n` +
    `Generated by Draftly.\n\n` +
    `## Notes\n` +
    `- Large binary assets (frames/video) may be omitted from GitHub push if too large for API commits.\n` +
    `- Use the in-app ZIP download for the full export.\n`;

  files['frontend/index.html'] = indexHtml;
  if (cssText) files['frontend/assets/css/main.css'] = cssText;
  if (jsText) files['frontend/assets/js/main.js'] = jsText;

  const enabledKits = params.enabledKits || [];
  const envExample = buildEnvExampleFromKitsAndExistingKeys({
    kits: enabledKits,
    existingEnvKeys: params.envKeys || [],
  });
  files['frontend/.env.example'] = envExample;
  files['frontend/INTEGRATIONS.md'] =
    `# Integration Kits\n\n` +
    `Enabled kits: ${enabledKits.length ? enabledKits.join(', ') : '(none)'}\n\n` +
    `Copy .env.example → .env.local and fill your own keys.\n`;
  const kitFiles = buildKitFiles(enabledKits, { appUrl: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000' });
  for (const [path, content] of Object.entries(kitFiles)) {
    files[`frontend/${path}`] = content;
  }
  // Uploaded images: keep a small subset to avoid blowing up repo size via API commit.
  const uploads = (params.uploadedImages || []).slice(0, 6);
  if (uploads.length) {
    files['frontend/assets/uploads/README.md'] =
      `Uploaded assets were included for layout binding. ` +
      `If you uploaded many images, use the ZIP export for the complete set.\n`;
    uploads.forEach((img, idx) => {
      const ext = img.dataUrl.startsWith('data:image/png') ? 'png' : 'jpg';
      const safeName = img.name?.replace(/[^a-zA-Z0-9._-]/g, '_') || `asset_${idx + 1}`;
      files[`frontend/assets/uploads/${String(idx + 1).padStart(2, '0')}_${safeName}.${ext}`] = img.dataUrl;
    });
  }

  // Frames/video are typically too large for GitHub API tree commits, so we omit them.
  // Users should use the ZIP export for full fidelity assets.
  if (params.siteRenderMode === 'frame-scroll') {
    files['frontend/frames-webp/README.md'] =
      `Frames are not included in GitHub push (too large for API commits). ` +
      `Download ZIP from Draftly to get frames-webp.\n`;
  }
  if (params.siteRenderMode === 'video-hero') {
    files['frontend/assets/video/README.md'] =
      `Video is not included in GitHub push (too large for API commits). ` +
      `Download ZIP from Draftly to get assets/video/hero.mp4.\n`;
  }

  return files;
}

export async function POST(req: NextRequest) {
  try {
    const auth = await verifyAuth(req);
    const { repoName, isPrivate = false, siteCode, siteRenderMode, webpFrames, videoBase64, uploadedImages } = await req.json();

    if (!repoName || typeof repoName !== 'string') {
      return NextResponse.json({ error: 'repoName required' }, { status: 400 });
    }
    if (!siteCode || typeof siteCode !== 'string') {
      return NextResponse.json({ error: 'siteCode required' }, { status: 400 });
    }

    const userDoc = await ensureUserDocument(auth.uid);
    const userData = userDoc.data() || {};
    const token = userData.githubAccessToken;
    const username = userData.githubUsername || (userData.email ? String(userData.email).split('@')[0] : '');
    const enabledKits: IntegrationKitId[] = Array.isArray((userData as any).enabledKits) ? (userData as any).enabledKits : [];
    const envKeys = Object.keys(((userData as any).envVars || {}) as Record<string, string>);

    if (!token) {
      return NextResponse.json(
        { error: 'GitHub not connected. Please connect GitHub in Integrations.', requiresAuth: true },
        { status: 401 },
      );
    }
    if (!username) {
      return NextResponse.json(
        { error: 'GitHub username missing. Reconnect GitHub in Integrations.' },
        { status: 400 },
      );
    }

    const files = buildFileMap({
      siteCode,
      siteRenderMode: siteRenderMode === 'video-hero' ? 'video-hero' : 'frame-scroll',
      webpFrames: Array.isArray(webpFrames) ? webpFrames : undefined,
      videoBase64: typeof videoBase64 === 'string' ? videoBase64 : null,
      uploadedImages: Array.isArray(uploadedImages) ? uploadedImages : undefined,
      enabledKits,
      envKeys,
    });

    const repo = await createGitHubRepository(
      { accessToken: token, username },
      repoName.trim(),
      'Generated by Draftly 3D Builder',
      files,
      Boolean(isPrivate),
    );

    // Persist the last pushed repo URL for convenience
    const db = getAdminDb();
    await db.collection('users').doc(auth.uid).set(
      {
        lastGitHubRepoUrl: repo.url,
        updatedAt: new Date().toISOString(),
      },
      { merge: true },
    );

    return NextResponse.json({ success: true, url: repo.url, repository: repo });
  } catch (err) {
    return authErrorResponse(err);
  }
}
