import { NextRequest, NextResponse } from 'next/server';
import { getAdminDb } from '@/lib/firebase-admin';
import { ensureUserDocument } from '@/lib/ensure-user-doc';
import { createGitHubRepository } from '@/lib/github-integration';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

export async function POST(req: NextRequest) {
  try {
    const { userId, projectId, repoName, isPrivate = false } = await req.json();

    if (!userId || !projectId || !repoName) {
      return NextResponse.json(
        { error: 'Missing required fields: userId, projectId, repoName' },
        { status: 400 }
      );
    }

    // Ensure user doc exists, then get GitHub token
    const db = getAdminDb();
    const userRef = db.collection('users').doc(userId);
    const userDoc = await ensureUserDocument(userId);
    const userData = userDoc.data();
    const githubToken = userData?.githubAccessToken;

    if (!githubToken) {
      return NextResponse.json(
        { 
          error: 'GitHub not connected. Please connect your GitHub account first.',
          requiresAuth: true,
        },
        { status: 401 }
      );
    }

    // Get project files
    const generationTracking = userData?.generationTracking || { projects: {} };
    const project = generationTracking.projects[projectId];

    if (!project) {
      return NextResponse.json(
        { error: 'Project not found' },
        { status: 404 }
      );
    }

    // Get GitHub username
    const githubUsername = userData?.githubUsername || userData?.email?.split('@')[0];

    // Create repository
    const repo = await createGitHubRepository(
      {
        accessToken: githubToken,
        username: githubUsername,
      },
      repoName,
      `Generated by Draftly: ${project.projectName}`,
      project.files,
      isPrivate
    );

    // Update project with GitHub URL
    generationTracking.projects[projectId] = {
      ...project,
      githubURL: repo.url,
    };

    await userRef.set({
      generationTracking,
      updatedAt: new Date().toISOString(),
    }, { merge: true });

    return NextResponse.json({
      success: true,
      repository: repo,
    });

  } catch (error: any) {
    console.error('GitHub repo creation error:', error);
    return NextResponse.json(
      { error: error?.message || 'Failed to create GitHub repository' },
      { status: 500 }
    );
  }
}

